version: "3"

services:
  server:
    build: todo-server
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes:
      - .:/code
    restart: on-failure
    depends_on:
      - mongo
  microtweet:
    build: microtweet-server
    environment:
      - S_HOST=redis
      - S_PORT=6379
      - SECRET=insertyoursecret
    networks:
      - webnet
    volumes:
      - .:/code_mt
    restart: on-failure
  client:
    build: angular-client
    ports:
      - "4200:4200"
    depends_on:
      - server
  mongo:
    image: "mongo:3.0.2"
    command: "--smallfiles"
    ports:
      - "27017:27017"
    networks:
      - webnet
  nginx:
    image: nginx:1.13.5
    ports:
      - "9000:80"
    restart: always
    volumes:
      - "./api-gateway/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - webnet
networks:
  webnet:
