version: "3"

services:
  server:
    build: todo-server
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes:
      - .:/code
    restart: on-failure
    depends_on:
      - mongo
  mongo:
    image: "mongo:3.0.2"
    command: "--smallfiles"
    ports:
      - "27017:27017"
    networks:
      - webnet
  client:
    build: angular-client
    ports:
      - "4200:4200"
    depends_on:
      - server

networks:
  webnet:
